---
- name: Provision the GCE Server
# =======================================
  hosts: localhost
  connection: local
  gather_facts: yes

  vars:
    zones:
      "1":  "asia-east1-a"
      "2":  "asia-east1-b"
      "3":  "asia-east1-c"
      "4":  "asia-east2-a"
      "5":  "asia-east2-b"
      "6":  "asia-east2-c"
      "7":  "asia-northeast1-a"
      "8":  "asia-northeast1-b"
      "9":  "asia-northeast1-c"
      "10": "asia-northeast2-a"
      "11": "asia-northeast2-b"
      "12": "asia-northeast2-c"
      "13": "asia-northeast3-a"
      "14": "asia-northeast3-b"
      "15": "asia-northeast3-c"
      "16": "asia-south1-a"
      "17": "asia-south1-b"
      "18": "asia-south1-c"
      "19": "asia-southeast1-a"
      "20": "asia-southeast1-b"
      "21": "asia-southeast1-c"
      "22": "asia-southeast2-a"
      "23": "asia-southeast2-b"
      "24": "asia-southeast2-c"
      "25": "australia-southeast1-a"
      "26": "australia-southeast1-b"
      "27": "australia-southeast1-c"
      "28": "europe-north1-a"
      "29": "europe-north1-b"
      "30": "europe-north1-c"
      "31": "europe-west1-b"
      "32": "europe-west1-c"
      "33": "europe-west1-d"
      "34": "europe-west2-a"
      "35": "europe-west2-b"
      "36": "europe-west2-c"
      "37": "europe-west3-a"
      "38": "europe-west3-b"
      "39": "europe-west3-c"
      "40": "europe-west4-a"
      "41": "europe-west4-b"
      "42": "europe-west4-c"
      "43": "europe-west6-a"
      "44": "seurope-west6-b"
      "45": "europe-west6-c"
      "46": "northamerica-northeast1-a"
      "47": "northamerica-northeast1-b"
      "48": "northamerica-northeast1-c"
      "49": "southamerica-east1-a"
      "50": "southamerica-east1-b"
      "51": "southamerica-east1-c"
      "52": "us-central1-a"
      "53": "us-central1-b"
      "54": "us-central1-c"
      "55": "us-central1-f"
      "56": "us-east1-b"
      "57": "us-east1-c"
      "58": "us-east1-d"
      "59": "us-east4-a"
      "60": "us-east4-b"
      "61": "us-east4-c"
      "62": "us-west1-a"
      "63": "us-west1-b"
      "64": "us-west1-c"
      "65": "us-west2-a"
      "66": "us-west2-b"
      "67": "us-west2-c"
      "68": "us-west3-a"
      "69": "us-west3-b"
      "70": "us-west3-c"
      "71": "us-west4-a"
      "72": "us-west4-b"
      "73": "us-west4-c"

  # These variable files are included so the gce-network role
  # knows which ports to open
  vars_files:
    - roles/openconnect/defaults/main.yml
    - roles/openvpn/defaults/main.yml
    - roles/shadowsocks/defaults/main.yml
    - roles/ssh/defaults/main.yml
    - roles/lets-encrypt/vars/main.yml
    - roles/streisand-gateway/defaults/main.yml
    - roles/stunnel/defaults/main.yml
    - roles/tor-bridge/defaults/main.yml
    - roles/wireguard/defaults/main.yml

  vars_prompt:
    - name: "gce_zone_idx"
      prompt: >
        What zone should the server be located in?
          1. asia-east1-a                (Changhua County, Taiwan)
          2. asia-east1-b                (Changhua County, Taiwan)
          3. asia-east1-c                (Changhua County, Taiwan)
          4. asia-east2-a                (Hong Kong)
          5. asia-east2-b                (Hong Kong)
          6. asia-east2-c                (Hong Kong)
          7. asia-northeast1-a           (Tokyo, Japan)
          8. asia-northeast1-b           (Tokyo, Japan)
          9. asia-northeast1-c           (Tokyo, Japan)
          10. asia-northeast2-a          (Osaka, Japan)
          11. asia-northeast2-b          (Osaka, Japan)
          12. asia-northeast2-c          (Osaka, Japan)
          13. asia-northeast3-a          (Seoul, South Korea)
          14. asia-northeast3-b          (Seoul, South Korea)
          15. asia-northeast3-c          (Seoul, South Korea)
          16. asia-south1-a              (Mumbai, India)
          17. asia-south1-b              (Mumbai, India)
          18. asia-south1-c              (Mumbai, India)
          19. asia-southeast1-a          (Jurong West, Singapore)
          20. asia-southeast1-b          (Jurong West, Singapore)
          21. asia-southeast1-c          (Jurong West, Singapore)
          22. asia-southeast2-a          (Jakarta, Indonesia)
          23. asia-southeast2-b          (Jakarta, Indonesia)
          24. asia-southeast2-c          (Jakarta, Indonesia)
          25. australia-southeast1-a     (Sydney, Australia)
          26. australia-southeast1-b     (Sydney, Australia)
          27. australia-southeast1-c     (Sydney, Australia)
          28. europe-north1-a            (Hamina, Finland)
          29. europe-north1-b            (Hamina, Finland)
          30. europe-north1-c            (Hamina, Finland)
          31. europe-west1-b             (St. Ghislain, Belgium)
          32. europe-west1-c             (St. Ghislain, Belgium)
          33. europe-west1-d             (St. Ghislain, Belgium)
          34. europe-west2-a             (London, England, UK)
          35. europe-west2-b             (London, England, UK)
          36. europe-west2-c             (London, England, UK)
          37. europe-west3-a             (Frankfurt, Germany)
          38. europe-west3-b             (Frankfurt, Germany)
          39. europe-west3-c             (Frankfurt, Germany)
          40. europe-west4-a             (Eemshaven, Netherlands)
          41. europe-west4-b             (Eemshaven, Netherlands)
          42. europe-west4-c             (Eemshaven, Netherlands)
          43. europe-west6-a             (Zürich, Switzerland)
          44. europe-west6-b             (Zürich, Switzerland)
          45. europe-west6-c             (Zürich, Switzerland)
          46. northamerica-northeast1-a  (Montréal, Québec, Canada)
          47. northamerica-northeast1-b  (Montréal, Québec, Canada)
          48. northamerica-northeast1-c  (Montréal, Québec, Canada)
          49. southamerica-east1-a       (Osasco (São Paulo), Brazil)
          50. southamerica-east1-b       (Osasco (São Paulo), Brazil)
          51. southamerica-east1-c       (Osasco (São Paulo), Brazil)
          52. us-central1-a              (Council Bluffs, Iowa, USA)
          53. us-central1-b              (Council Bluffs, Iowa, USA)
          54. us-central1-c              (Council Bluffs, Iowa, USA)
          55. us-central1-f              (Council Bluffs, Iowa, USA)
          56. us-east1-b                 (Moncks Corner, South Carolina, USA)
          57. us-east1-c                 (Moncks Corner, South Carolina, USA)
          58. us-east1-d                 (Moncks Corner, South Carolina, USA)
          59. us-east4-a                 (Ashburn, Northern Virginia, USA)
          60. us-east4-b                 (Ashburn, Northern Virginia, USA)
          61. us-east4-c                 (Ashburn, Northern Virginia, USA)
          62. us-west1-a                 (The Dalles, Oregon, USA)
          63. us-west1-b                 (The Dalles, Oregon, USA)
          64. us-west1-c                 (The Dalles, Oregon, USA)
          65. us-west2-a                 (Los Angeles, California, USA)
          66. us-west2-b                 (Los Angeles, California, USA)
          67. us-west2-c                 (Los Angeles, California, USA)
          68. us-west3-a                 (Salt Lake City, Utah, USA)
          69. us-west3-b                 (Salt Lake City, Utah, USA)
          70. us-west3-c                 (Salt Lake City, Utah, USA)
          71. us-west4-a                 (Las Vegas, Nevada, USA)
          72. us-west4-b                 (Las Vegas, Nevada, USA)
          73. us-west4-c                 (Las Vegas, Nevada, USA)
        Please choose the number of your zone. Press enter for default (#53) zone.
      default: "53"
      when: gce_zone is not defined
      private: no

    - name: "gce_server_name"
      prompt: "\nWhat should the server be named? Press enter for default (streisand).\n"
      default: "streisand-server"
      private: no

    - name: "gce_json_file_location"
      prompt: "\n\nThe full path of your unique service account credentials file. Details on generating this can be found at \nhttps://docs.ansible.com/ansible/guide_gce.html#credentials\n and \nhttps://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts\n"
      default: "{{ lookup('env','HOME') }}/streisand.json"
      private: no

    - name: "confirmation"
      prompt: "\nStreisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...\n"

  pre_tasks:
    - name: Set the Google Compute Engine Zone interactive
      set_fact:
        gce_zone: "{{ zones[gce_zone_idx] }}"
      when: gce_zone is not defined

    - name: Register JSON file contents
      command: cat {{ gce_json_file_location }}
      register: gce_json_file_contents
      changed_when: False

    - name: Set JSON file contents fact
      set_fact:
        gce_json_contents_fact: "{{ gce_json_file_contents.stdout | from_json }}"

    - name: Set the Google Compute Engine Service Account Email
      set_fact:
        gce_service_account_email: "{{ gce_json_contents_fact.client_email }}"

    - name: Set the Google Compute Engine Project ID
      set_fact:
        gce_project_id: "{{ gce_json_contents_fact.project_id }}"

  roles:
    - genesis-google

- import_playbook: ssh-setup.yml
- import_playbook: cloud-status.yml
- import_playbook: streisand.yml
...
